export const mockMedicamentos = [
  {
    id: 1,
    codigo: "dasd12312",
    nombre: "Paracetamol",
    categoria: "Analgésico",
    lote: "edasd",
    registro_sanitario: "EERWD3132",
    laboratio: "Biopharm",
    stock: 50,
    caducidad: 10 / 12 / 2025,
  },
  {
    id: 2,
    codigo: "dasd12312",
    nombre: "Paracetamol",
    categoria: "Analgésico",
    lote: "edasd",
    registro_sanitario: "EERWD3132",
    laboratio: "Biopharm",
    stock: 50,
    caducidad: 10 / 12 / 2025,
  },
  {
    id: 3,
    codigo: "dasd12312",
    nombre: "Paracetamol",
    categoria: "Analgésico",
    lote: "edasd",
    registro_sanitario: "EERWD3132",
    laboratio: "Biopharm",
    stock: 50,
    caducidad: 10 / 12 / 2025,
  },
];
